spring.application.name=BloggingApp
spring.datasource.url = jdbc:postgresql://localhost:5432/bloggingapp
spring.datasource.username = postgres
spring.datasource.password = raja2019
# auto-create/update tables based on entities
spring.jpa.hibernate.ddl-auto=update

# optional: log SQL queries
spring.jpa.show-sql=true
